wip

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -17,14 +17,19 @@ INSTALL_DIR="$BUILD_DIR/.heroku/vendor/buildout"  # -> after buildout is
 mkdir -p $CACHE_DIR
 mkdir -p $INSTALL_DIR
 
-if [ -f $ENV_DIR/PYPICLOUD_USERNAME ] && [ -f $ENV_DIR/PYPICLOUD_PASSWORD ]; then
-    echo "-----> Use PYPICLOUD credentials"
+if ! [ -f $BUILD_DIR/bootstrap.py ]; then
+    echo "-----> File bootstrap.py not found, failing." | indent
+    exit 1
+fi
+
+if [ -f $ENV_DIR/PYPI_USERNAME ] && [ -f $ENV_DIR/PYPI_PASSWORD ] && [ -f $ENV_DIR/PYPI_URL ]; then
+    echo "-----> Use Third-party PYPI"
     echo "[distutils]" >> ~/.pypirc
-    echo "index-servers = pypicloud" >> ~/.pypirc
-    echo "[pypicloud]" >> ~/.pypirc
-    echo "repository = https://pypicloud.niteoweb.com" >> ~/.pypirc
-    echo "username = $(cat $ENV_DIR/PYPICLOUD_USERNAME)" >> ~/.pypirc
-    echo "password = $(cat $ENV_DIR/PYPICLOUD_PASSWORD)" >> ~/.pypirc
+    echo "index-servers = third_party_pypi" >> ~/.pypirc
+    echo "[third_party_pypi]" >> ~/.pypirc
+    echo "repository = $(cat $ENV_DIR/PYPI_URL)" >> ~/.pypirc
+    echo "username = $(cat $ENV_DIR/PYPI_USERNAME)" >> ~/.pypirc
+    echo "password = $(cat $ENV_DIR/PYPI_PASSWORD)" >> ~/.pypirc
 fi
 
 echo "-----> Use build cache"
@@ -58,15 +63,6 @@ else
     echo "Use default buildout verbosity" | indent
 fi
 
-echo "-----> Read BOOTSTRAP_PY_URL from env vars, or use default"
-if [ -f $ENV_DIR/BOOTSTRAP_PY_URL ]; then
-    export "BOOTSTRAP_PY_URL=$(cat $ENV_DIR/BOOTSTRAP_PY_URL)"
-    echo "Use custom bootstrap.py: ${BOOTSTRAP_PY_URL}" | indent
-else
-    export "BOOTSTRAP_PY_URL=http://downloads.buildout.org/2/bootstrap.py"
-    echo "Use default bootstrap.py: ${BOOTSTRAP_PY_URL}" | indent
-fi
-
 # create a symlink to where python will be located when this slug is in
 # heroku runtime
 #mkdir -p /app/.heroku/python/bin/
@@ -76,7 +72,6 @@ cd $BUILD_DIR
 export "PYTHON_VERSION=$(/app/.heroku/python/bin/python --version)"
 echo "-----> Bootstrap buildout using Python provided by heroku-buildpack-python:"
 echo "$PYTHON_VERSION" | indent
-curl -OL "${BOOTSTRAP_PY_URL}"
 #/app/.heroku/python/bin/python bootstrap.py -c $BUILDOUT_CFG
 python bootstrap.py -c $BUILDOUT_CFG
 
